//! Base256 armored encoding for rsg/rsm data.
//!
//! Python ref: 1.3.8 `RNS/__init__.py` `b256`/`b256rep`/`b256_to_bytes` (commit
//! 855ef7bf). Upstream marks the glyph table experimental ("likely to change") —
//! this is the 1.3.8 snapshot; re-check on upstream release sweeps.

use std::collections::HashMap;
use std::sync::LazyLock;

/// One glyph per byte value 0x00..=0xFF, in upstream table order
/// (Latin/numerals, Greek, Cyrillic, Armenian, Elder Futhark, Katakana,
/// Shavian, Ol Chiki, Gothic & Deseret).
const B256_GLYPHS: &str = "abcdefghijklmnopqrstuvxyzæø01234\
ABCDEFGHIJKLMNOPQRSTUWXYZÆØ56789\
αβγδεζηθικλμνξπρστφχψωΓΔΘΛΞΠΣΦΨΩ\
БДЖЗИЛПЦЧШЩЪЫЭЮЯбджзилпцчшщъыэюя\
ԱԲԳԴԵԶԷԸԹԺԻԽԾԿՀՁՂՃՄՅՆՇՈՉՊՋՎՐՑՒՔՖ\
ᚠᚢᚦᚱᚹᚺᚾᛈᛇᛉᛊᛏᛒᛖᛗᛟ\
ｲｳｵｶｷｹｻｼｽｾﾀﾁﾃﾄﾅﾇ\
ﾈﾋﾌﾍﾎﾏﾐﾑﾒﾓﾔﾗﾘﾙﾚﾜ\
𐑐𐑑𐑒𐑔𐑕𐑗𐑙𐑳𐑶𐑸𐑹𐑺𐑻𐑽𐑾𐑿\
᱑᱕᱘᱙ᱚᱝᱟᱣᱦᱨᱬᱭᱰᱳᱶᱷ\
𐌳𐌸𐌾𐐀𐐁𐐂𐐆𐐇𐐈𐐉𐐊𐐋𐐌𐐍𐐎𐐏";

static B256: LazyLock<Vec<char>> = LazyLock::new(|| {
    let table: Vec<char> = B256_GLYPHS.chars().collect();
    assert_eq!(table.len(), 256, "b256 glyph table must hold 256 entries");
    table
});

static B256_INDEX: LazyLock<HashMap<char, u8>> = LazyLock::new(|| {
    B256.iter()
        .enumerate()
        .map(|(index, glyph)| (*glyph, index as u8))
        .collect()
});

pub fn b256rep(data: &[u8]) -> String {
    data.iter().map(|byte| B256[*byte as usize]).collect()
}

#[allow(dead_code)]
pub fn b256_to_bytes(input: &str) -> Result<Vec<u8>, String> {
    input
        .chars()
        .map(|glyph| {
            B256_INDEX
                .get(&glyph)
                .copied()
                .ok_or_else(|| format!("Could not decode base256: invalid glyph {glyph:?}"))
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    // Generated by running the verbatim 1.3.8 RNS/__init__.py b256 helpers over
    // bytes(range(256)) — proves the table copy is glyph-for-glyph faithful.
    const PYTHON_138_ALL_BYTES: &str = "abcdefghijklmnopqrstuvxyzæø01234ABCDEFGHIJKLMNOPQRSTUWXYZÆØ56789αβγδεζηθικλμνξπρστφχψωΓΔΘΛΞΠΣΦΨΩБДЖЗИЛПЦЧШЩЪЫЭЮЯбджзилпцчшщъыэюяԱԲԳԴԵԶԷԸԹԺԻԽԾԿՀՁՂՃՄՅՆՇՈՉՊՋՎՐՑՒՔՖᚠᚢᚦᚱᚹᚺᚾᛈᛇᛉᛊᛏᛒᛖᛗᛟｲｳｵｶｷｹｻｼｽｾﾀﾁﾃﾄﾅﾇﾈﾋﾌﾍﾎﾏﾐﾑﾒﾓﾔﾗﾘﾙﾚﾜ𐑐𐑑𐑒𐑔𐑕𐑗𐑙𐑳𐑶𐑸𐑹𐑺𐑻𐑽𐑾𐑿᱑᱕᱘᱙ᱚᱝᱟᱣᱦᱨᱬᱭᱰᱳᱶᱷ𐌳𐌸𐌾𐐀𐐁𐐂𐐆𐐇𐐈𐐉𐐊𐐋𐐌𐐍𐐎𐐏";

    #[test]
    fn matches_python_138_table() {
        let all_bytes: Vec<u8> = (0..=255u8).collect();
        assert_eq!(b256rep(&all_bytes), PYTHON_138_ALL_BYTES);
    }

    #[test]
    fn round_trips_all_byte_values() {
        let all_bytes: Vec<u8> = (0..=255u8).collect();
        let encoded = b256rep(&all_bytes);
        assert_eq!(b256_to_bytes(&encoded).unwrap(), all_bytes);
    }

    #[test]
    fn decode_rejects_unknown_glyph() {
        assert!(b256_to_bytes("ab!").is_err());
        // 'w' and 'V' are deliberately absent from the upstream table.
        assert!(b256_to_bytes("w").is_err());
        assert!(b256_to_bytes("V").is_err());
    }
}
